swagger: '2.0'
info:
  version: '0.1'
  title: 'cmu mars brass th: phase 2, cp2'
schemes:
  - http
host: brass-th
paths:
  /error:
    post:
      consumes:
        - application/json
      description: |-
        Used to indicate that an error has occurred during the preparation
        or evaluation of a test scenario, or during the start-up of the
        system under test.
      parameters:
        - in: body
          required: true
          name: Parameters
          schema:
            type: object
            $ref: './cp2-definitions.yaml#/definitions/Error'
      responses:
        '204':
          description: the TH acknowledges the error
        '400':
          description: the TH has itself encountered an error processing the error

  /ready:
    post:
      description: >-
        Used to indicate that the SUT is ready and that testing may begin.
      produces:
        - application/json
      responses:
        '200':
          description: the TH acknowledges the ready message
          schema:
            type: object
            properties:
              bugzoo-server-urls:
                type: array
                items:
                  type: string
                  example: 'http://127.0.0.1:6060'
                description: >-
                  A list of the base URLs for all BugZoo servers that have been
                  made available for the purpose of evaluating candidate
                  patches.
        '400':
          description: the TH has itself encountered an error processing the ready message

  /status:
    post:
      description: >-
        Used to inform the test harness that a new adaptation has been added to
        the Pareto set (i.e., a new "best" adaptation has been found).
      consumes:
        - application/json
      parameters:
        - in: body
          required: true
          name: Parameters
          schema:
            type: object
            required:
              - adaptation
              - pareto-set
            properties:
              adaptation:
                type: object
                $ref: './cp2-definitions.yaml#/definitions/CandidateAdaptation'
                description: The candidate adaptation that was added to the
                  Pareto set.
              pareto-set:
                type: array
                items:
                  $ref: './cp2-definitions.yaml#/definitions/CandidateAdaptation'
                description: The current contents of the Pareto-set of adaptations.
      responses:
        '204':
          description: the TH acknowledges the status
        '400':
          description: the TH has itself encontered an error processing the status

  /done:
    post:
      description: >-
        Used to indicate that evaluation of the test scenario has been
        completed. A summary of the results of the test scenario are provided as
        a JSON object. The entire summary is contained within
        `SutFinishedStatus`, as specified by the Lincoln Labs API.
      parameters:
        - in: body
          required: true
          name: Parameters
          schema:
            type: object
            required:
              - outcome
              - running-time
              - num-attempts
              - pareto-set
              - log
            properties:
              outcome:
                type: string
                enum:
                  - complete-repair
                  - partial-repair
                  - no-repair
                description: >-
                  A short description of the success of the repair process.
                  A complete repair is one which passes all of the tests in the
                  test suite. A partial repair is one that passes at least one
                  previously failing test and does not introduce any new test
                  failures. If the outcome of the test suite for the best patch
                  found during the search does cause any previously failing
                  tests to pass, then no repair has been found.
              running-time:
                type: number
                format: float
                minimum: 0
                description: >-
                  The number of minutes taken to complete the repair process.
              num-attempts:
                type: integer
                minimum: 0
                description: >-
                  The number of code adaptations attempted.
              pareto-set:
                type: array
                items:
                  $ref: './cp2-definitions.yaml#/definitions/CandidateAdaptation'
                description: >-
                  A list containing details of all adaptations within the
                  pareto set.
              log:
                type: array
                items:
                  $ref: './cp2-definitions.yaml#/definitions/CandidateAdaptation'
                description: >-
                  A list containing details of each of the attempted repairs.
      responses:
        '204':
          description: the TH acknowledges the done message
        '400':
          description: the TH has itself encountered an error processing the done message
