swagger: '2.0'
info:
  version: '0.1'
  title: 'CP3 Internal Status API'
schemes:
  - http
host: brass-ta
paths:
  /internal-status:
    post:
      description: >-
        reports any internal status that might be sent to the TA for internal
        bookeeping or forwarding to the TH
      parameters:
        - in: body
          name: CP3InternalStatus
          required: true
          schema:
            type: object
            required:
              - status
              - message
              - sim-time
            properties:
              status:
                description: >-
                  one of a enumerated set of statuses to report, arise, as
                  follows:
                    * `RAINBOW_READY`, Rainbow is up and ready for the mission
                      to start

                    * `MISSION_SUCCEEDED`, According to the SUT, the mission has
                      successfully completed. This will only be reported in the
                      Challenge case.

                    * `MISSION_FAILED`, According to the SUT, the mission has
                      failed. This will only be reported in the Challenge case.

                    * `ADAPTING`, the SUT has started adapting, which means looking
                      for a new plan.

                    * `ADAPTED`, the SUT has found a new plan and it has been issued to
                      the system.

                    * `ADAPTED_FAILED`, the plan failed to be executed on the system

                    * `FINAL_UTILITY` the final utility achieved by
                      the system. Here the message will simply be a
                      floating point number printed as a string

                    * `PLAN` the new list of waypoints being visted by
                      the system because of replanning. The message
                      will be a stringified json array of strings.

                type: string
                enum:
                  - RAINBOW_READY
                  - MISSION_SUCCEEDED
                  - MISSION_FAILED
                  - ADAPTING
                  - ADAPTED
                  - ADAPTED_FAILED
                  - FINAL_UTILITY
                  - PLAN
              message:
                description: 'human readable text describing the status, if any'
                type: string
              sim-time:
                type: integer
                minimum: 0
                description: the simulation time the status message was produced
      responses:
        '200':
          description: the TH acknowledges the status of the SUT
        '400':
          description: the TH has encountered an error in processing the status of the SUT
