swagger: '2.0'
info:
  version: '0.1'
  title: 'cmu mars brass th: phase 2, cp3'
schemes:
  - http
host: brass-th
definitions:
  CollisionData:
    type: object
    required:
      - robot-x
      - robot-y
      - robot-speed
      - sim-time
    properties:
      robot-x:
        type: number
        format: float
        description: >-
          The x location of the robot center when collision occured
      robot-y:
        type: number
        format: float
        description: >-
          The y lcoation of the robot center when collision occured
      robot-speed:
        type: number
        format: float
        description: >-
          The speed of the robot (m/s) at the time the collision occured
      sim-time:
        type: integer
        description: >-
          The (simulation) time at which the collision occurred (seconds from start of simulator)
paths:
  /ready:
    post:
      description: >-
        indicates that the SUT is ready to recieve configuration data to
        continue start up
      responses:
        '200':
          description: TH is ready to produce configuration data
          schema:
            type: object
            properties:
              start-loc:
                type: string
                description: >-
                  the name of the start map waypoint. must be a valid way
                  point name from the map data. must not be equal to
                  `target-loc`.
              target-loc:
                type: string
                description: >-
                  the name of the goal map waypoint. must be a valid way
                  point name from the map data. must not be equal to
                  `start-loc`.
              use-adaptation:
                type: boolean
                description: >-
                  if `true`, then the DAS will use adapative behaiviours; if
                  `false` then the DAS will not use adaptive behaiviours
              start-configuration:
                type: string
                description: >-
                  the label of the starting configuration for the robot
                enum:
                  - amcl-kinect
                  - amcl-lidar
                  - mprt-kinect
                  - mprt-lidar
                  - aruco-camera
              utility-function:
                type: string
                description: >-
                  the utility function to use for evaluating mission quality
                enum:
                  - favor-timeliness
                  - favor-safety
                  - favor-efficiency
        '400':
          description: TH encountered an error producing configuration data
  /error:
    post:
      description: >-
        indicates that the SUT has encountered an error in configuration data,
        parameters, system start, or any other less specified problem
      parameters:
        - in: body
          name: Parameters
          required: true
          schema:
            type: object
            required:
              - error
            properties:
              message:
                description: >-
                  human readable text describing the error, if
                  possible. (TODO: add error codes here as we discover them)
                type: string
      responses:
        '200':
          description: >-
            the TH acknowledges that the SUT has encountered an error and will
            shut down the test
        '400':
          description: >-
            the TH has encountered an error in processing the error from the SUT
            and will also shut down the test
  /status:
    post:
      description: >-
        indicate important state changes in the SUT to the TH. posted
        periodically as the described events occur.
      parameters:
        - in: body
          name: Parameters
          required: true
          schema:
            type: object
            required:
              - status
              - sim-time
            properties:
              status:
                description: >-
                  one of a enumerated set of statuses to report,
                  arise, as follows:
                    * `live`, the SUT has processed the configuration data
                       and is ready for initial perturbations (if any) and the
                       start of the test

                    * `mission-running`, the SUT has processed the initial
                       perturbations after receiving `/start`, possibly
                       adapted, and the robot is now actually moving along
                       its path. it is an error to send any perturbation to
                       the SUT between sending a message to `/start` and
                       receiving this status.

                    * `adapting`, the SUT has detected a condition that
                       requires adaptation and the SUT is adapting. it is
                       an error to send any perturbation to the SUT after
                       this message is sent to the TH until the TH gets a
                       status message with `adapted`.

                    * `adapted`, the SUT has finished adapting after
                       observing a need to. this means that the robot is
                       moving along its plan again and it is no longer an
                       error to send perturbations. if this is the status
                       code of the message, the fields `plan`, `config` and
                       `sensors` will also be present, to describe the new
                       state of the robot.
                type: string
                enum:
                  - live
                  - mission-running
                  - adapting
                  - adapted
              message:
                description: human readable text describing the status, if any
                type: string
              sim-time:
                type: integer
                minimum: 0
                description: >-
                  the simulation time the status message was produced
              plan:
                description: >-
                  list of waypoints the current plan tends to visit, in
                  order. This will not be sent with `status == live`.
                type: array
                items:
                  type: string
              config:
                description: >-
                  list of currently active nodes. This will not be sent
                  with `status == live`.
                type: array
                items:
                  type: string
                  enum:
                    - amcl-kinect
                    - amcl-lidar
                    - mrpt-kinect
                    - mrpt-lidar
                    - aruco-camera
              sensors:
                description: >-
                  list of currently active sensors, in order. This will
                  not be sent with `status == live`.
                type: array
                items:
                  type: string
                  enum:
                    - kinect
                    - lidar
                    - camera
                    - headlamp
      responses:
        '200':
          description: the TH acknowledges the status of the SUT
        '400':
          description: the TH has encountered an error in processing the status of the SUT
  /done:
    post:
      description: indicates that the test is completed
      parameters:
        - in: body
          name: Parameters
          required: true
          schema:
            type: object
            required:
              - final-x
              - final-y
              - final-sim-time
              - final-charge
              - collisions
              - num-adaptations
              - final-utility
            properties:
              final-x:
                type: number
                format: float
                description: >-
                  the x coordinate of the robot position when the test ended
              final-y:
                type: number
                format: float
                description: >-
                  the y coordinate of the robot position when the test ended
              final-sim-time:
                type: integer
                minimum: 0
                description: the simulation time when the mission finished
              final-charge:
                type: integer
                minimum: 0
                description: >-
                  the charge left in the battery when the test ended
              collisions:
                type: array
                items:
                  $ref: "#/definitions/CollisionData"
                description: >-
                  A (possibly empty) list of locations, times, and speeds of any collisions of the robot
              num-adaptations:
                type: integer
                minimum: 0
                description: >-
                  the number of times that the robot adapted (0 if there is no DAS)
              final-utility:
                type: number
                format: float
                minimum: 0.0
                maximum: 1.0
                description: >-
                  the utility achieved at the end of the mission, in the range [0,1]
      responses:
        '200':
          description: >-
            the TH acknowledges the done message from the SUT and is shutting
            down the test
        '400':
          description: >-
            the TH has encountered an error in processing the done message of
            the SUT and is shutting down the test
